let express=require("express")
const { add, login, sendotp, votp, pwdreset, getemp } = require("../controlers/empcont")
const { addtask, admindisp, empdisp, updstatus, del } = require("../controlers/taskcont")
let rt=new express.Router()
rt.post("/reg",add)
rt.post("/login",login)
rt.get("/sendotp/:id",sendotp)
rt.get("/votp/:id/:otp",votp)
rt.put("/pwdreset",pwdreset)
rt.post("/addtask",addtask)
rt.get("/disp",admindisp)
rt.get("/disp/:eid",empdisp)
rt.get("/getemp/:dept",getemp)
rt.get("/updstatus/:tid/:st",updstatus)
rt.delete("/del/:tid",del)
module.exports=rt